# Generated by Django 3.1.5 on 2021-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
