# Generated by Django 3.1.5 on 2021-03-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zipcode',
            new_name='street',
        ),
    ]
